export const seedCountries = [
  { nameEn: "Egypt", nameAr: "مصر" },
  { nameEn: "Saudi Arabia", nameAr: "المملكة العربية السعودية" },
  { nameEn: "Jordan", nameAr: "الأردن" },
  { nameEn: "UAE", nameAr: "الإمارات العربية المتحدة" },
  { nameEn: "Kuwait", nameAr: "الكويت" },
  { nameEn: "Bahrain", nameAr: "البحرين" },
  { nameEn: "Qatar", nameAr: "قطر" },
  { nameEn: "Oman", nameAr: "عُمان" },
  { nameEn: "Iraq", nameAr: "العراق" },
  { nameEn: "Syria", nameAr: "سوريا" },
  { nameEn: "Lebanon", nameAr: "لبنان" },
  { nameEn: "Palestine", nameAr: "فلسطين" },
  { nameEn: "Yemen", nameAr: "اليمن" },
  { nameEn: "Libya", nameAr: "ليبيا" },
  { nameEn: "Tunisia", nameAr: "تونس" },
  { nameEn: "Algeria", nameAr: "الجزائر" },
  { nameEn: "Morocco", nameAr: "المغرب" },
  { nameEn: "Sudan", nameAr: "السودان" },
  { nameEn: "Somalia", nameAr: "الصومال" },
  { nameEn: "Mauritania", nameAr: "موريتانيا" },
  { nameEn: "Djibouti", nameAr: "جيبوتي" },
  { nameEn: "Comoros", nameAr: "جزر القمر" },
];

export interface GovSeed {
  nameEn: string;
  nameAr: string;
  areas: { nameEn: string; nameAr: string }[];
}

export const seedGovernorates: Record<string, GovSeed[]> = {
  "Egypt": [
    { nameEn: "Cairo", nameAr: "القاهرة", areas: [
      { nameEn: "Maadi", nameAr: "المعادي" },
      { nameEn: "Nasr City", nameAr: "مدينة نصر" },
      { nameEn: "Heliopolis", nameAr: "مصر الجديدة" },
      { nameEn: "Zamalek", nameAr: "الزمالك" },
      { nameEn: "Downtown", nameAr: "وسط البلد" },
      { nameEn: "Shubra", nameAr: "شبرا" },
      { nameEn: "Ain Shams", nameAr: "عين شمس" },
      { nameEn: "El Marg", nameAr: "المرج" },
      { nameEn: "New Cairo", nameAr: "القاهرة الجديدة" },
      { nameEn: "El Shorouk", nameAr: "الشروق" },
      { nameEn: "El Rehab", nameAr: "الرحاب" },
      { nameEn: "Madinaty", nameAr: "مدينتي" },
    ] },
    { nameEn: "Alexandria", nameAr: "الإسكندرية", areas: [
      { nameEn: "Smouha", nameAr: "سموحة" },
      { nameEn: "Mandara", nameAr: "المندرة" },
      { nameEn: "Montazah", nameAr: "المنتزه" },
      { nameEn: "Sidi Gaber", nameAr: "سيدي جابر" },
      { nameEn: "Gleem", nameAr: "جليم" },
      { nameEn: "Agami", nameAr: "العجمي" },
      { nameEn: "Borg El Arab", nameAr: "برج العرب" },
      { nameEn: "Raml Station", nameAr: "محطة الرمل" },
    ] },
    { nameEn: "Giza", nameAr: "الجيزة", areas: [
      { nameEn: "Dokki", nameAr: "الدقي" },
      { nameEn: "Mohandessin", nameAr: "المهندسين" },
      { nameEn: "Haram", nameAr: "الهرم" },
      { nameEn: "Faisal", nameAr: "فيصل" },
      { nameEn: "Sheikh Zayed", nameAr: "الشيخ زايد" },
      { nameEn: "6th of October City", nameAr: "مدينة السادس من أكتوبر" },
      { nameEn: "Agouza", nameAr: "العجوزة" },
      { nameEn: "Imbaba", nameAr: "إمبابة" },
    ] },
    { nameEn: "Port Said", nameAr: "بورسعيد", areas: [
      { nameEn: "Al Arab", nameAr: "العرب" },
      { nameEn: "Al Manakh", nameAr: "المناخ" },
      { nameEn: "Port Fouad", nameAr: "بور فؤاد" },
    ] },
    { nameEn: "Suez", nameAr: "السويس", areas: [
      { nameEn: "Suez City", nameAr: "مدينة السويس" },
      { nameEn: "Ain Sokhna", nameAr: "العين السخنة" },
    ] },
    { nameEn: "Dakahlia", nameAr: "الدقهلية", areas: [
      { nameEn: "Mansoura", nameAr: "المنصورة" },
      { nameEn: "Talkha", nameAr: "طلخا" },
      { nameEn: "Mit Ghamr", nameAr: "ميت غمر" },
    ] },
    { nameEn: "Sharqia", nameAr: "الشرقية", areas: [
      { nameEn: "Zagazig", nameAr: "الزقازيق" },
      { nameEn: "10th of Ramadan", nameAr: "العاشر من رمضان" },
      { nameEn: "Belbeis", nameAr: "بلبيس" },
    ] },
    { nameEn: "Qalyubia", nameAr: "القليوبية", areas: [
      { nameEn: "Banha", nameAr: "بنها" },
      { nameEn: "Shubra El Kheima", nameAr: "شبرا الخيمة" },
      { nameEn: "Qalyub", nameAr: "قليوب" },
      { nameEn: "El Obour", nameAr: "العبور" },
    ] },
    { nameEn: "Kafr El Sheikh", nameAr: "كفر الشيخ", areas: [] },
    { nameEn: "Gharbia", nameAr: "الغربية", areas: [
      { nameEn: "Tanta", nameAr: "طنطا" },
      { nameEn: "El Mahalla El Kubra", nameAr: "المحلة الكبرى" },
    ] },
    { nameEn: "Monufia", nameAr: "المنوفية", areas: [
      { nameEn: "Shibin El Kom", nameAr: "شبين الكوم" },
      { nameEn: "Menouf", nameAr: "منوف" },
    ] },
    { nameEn: "Beheira", nameAr: "البحيرة", areas: [
      { nameEn: "Damanhour", nameAr: "دمنهور" },
      { nameEn: "Kafr El Dawar", nameAr: "كفر الدوار" },
    ] },
    { nameEn: "Ismailia", nameAr: "الإسماعيلية", areas: [
      { nameEn: "Ismailia City", nameAr: "مدينة الإسماعيلية" },
    ] },
    { nameEn: "Damietta", nameAr: "دمياط", areas: [] },
    { nameEn: "Beni Suef", nameAr: "بني سويف", areas: [] },
    { nameEn: "Faiyum", nameAr: "الفيوم", areas: [] },
    { nameEn: "Minya", nameAr: "المنيا", areas: [
      { nameEn: "Minya City", nameAr: "مدينة المنيا" },
      { nameEn: "Mallawi", nameAr: "ملوي" },
    ] },
    { nameEn: "Asyut", nameAr: "أسيوط", areas: [
      { nameEn: "Asyut City", nameAr: "مدينة أسيوط" },
    ] },
    { nameEn: "Sohag", nameAr: "سوهاج", areas: [
      { nameEn: "Sohag City", nameAr: "مدينة سوهاج" },
    ] },
    { nameEn: "Qena", nameAr: "قنا", areas: [] },
    { nameEn: "Aswan", nameAr: "أسوان", areas: [
      { nameEn: "Aswan City", nameAr: "مدينة أسوان" },
    ] },
    { nameEn: "Luxor", nameAr: "الأقصر", areas: [
      { nameEn: "Luxor City", nameAr: "مدينة الأقصر" },
    ] },
    { nameEn: "Red Sea", nameAr: "البحر الأحمر", areas: [
      { nameEn: "Hurghada", nameAr: "الغردقة" },
      { nameEn: "Marsa Alam", nameAr: "مرسى علم" },
    ] },
    { nameEn: "New Valley", nameAr: "الوادي الجديد", areas: [] },
    { nameEn: "Matrouh", nameAr: "مطروح", areas: [] },
    { nameEn: "North Sinai", nameAr: "شمال سيناء", areas: [] },
    { nameEn: "South Sinai", nameAr: "جنوب سيناء", areas: [
      { nameEn: "Sharm El Sheikh", nameAr: "شرم الشيخ" },
      { nameEn: "Dahab", nameAr: "دهب" },
    ] },
  ],
  "Saudi Arabia": [
    { nameEn: "Riyadh", nameAr: "الرياض", areas: [
      { nameEn: "Olaya", nameAr: "العليا" },
      { nameEn: "Malaz", nameAr: "الملز" },
      { nameEn: "Al Murabba", nameAr: "المربع" },
      { nameEn: "Al Sulaymaniyah", nameAr: "السليمانية" },
      { nameEn: "Al Naseem", nameAr: "النسيم" },
      { nameEn: "Al Rawdah", nameAr: "الروضة" },
      { nameEn: "Al Diriyah", nameAr: "الدرعية" },
      { nameEn: "Al Kharj", nameAr: "الخرج" },
    ] },
    { nameEn: "Makkah", nameAr: "مكة المكرمة", areas: [
      { nameEn: "Makkah City", nameAr: "مكة المكرمة" },
      { nameEn: "Jeddah", nameAr: "جدة" },
      { nameEn: "Taif", nameAr: "الطائف" },
      { nameEn: "Rabigh", nameAr: "رابغ" },
      { nameEn: "Al Laith", nameAr: "الليث" },
    ] },
    { nameEn: "Madinah", nameAr: "المدينة المنورة", areas: [
      { nameEn: "Madinah City", nameAr: "المدينة المنورة" },
      { nameEn: "Yanbu", nameAr: "ينبع" },
      { nameEn: "Al Ula", nameAr: "العلا" },
      { nameEn: "Badr", nameAr: "بدر" },
    ] },
    { nameEn: "Eastern Province", nameAr: "المنطقة الشرقية", areas: [
      { nameEn: "Dammam", nameAr: "الدمام" },
      { nameEn: "Dhahran", nameAr: "الظهران" },
      { nameEn: "Al Khobar", nameAr: "الخبر" },
      { nameEn: "Al Jubail", nameAr: "الجبيل" },
      { nameEn: "Al Ahsa", nameAr: "الأحساء" },
      { nameEn: "Al Qatif", nameAr: "القطيف" },
      { nameEn: "Hafar Al Batin", nameAr: "حفر الباطن" },
    ] },
    { nameEn: "Asir", nameAr: "عسير", areas: [
      { nameEn: "Abha", nameAr: "أبها" },
      { nameEn: "Khamis Mushait", nameAr: "خميس مشيط" },
    ] },
    { nameEn: "Tabuk", nameAr: "تبوك", areas: [
      { nameEn: "Tabuk City", nameAr: "مدينة تبوك" },
      { nameEn: "NEOM", nameAr: "نيوم" },
    ] },
    { nameEn: "Hail", nameAr: "حائل", areas: [
      { nameEn: "Hail City", nameAr: "مدينة حائل" },
    ] },
    { nameEn: "Northern Borders", nameAr: "الحدود الشمالية", areas: [] },
    { nameEn: "Jizan", nameAr: "جازان", areas: [
      { nameEn: "Jizan City", nameAr: "مدينة جازان" },
    ] },
    { nameEn: "Najran", nameAr: "نجران", areas: [] },
    { nameEn: "Al-Bahah", nameAr: "الباحة", areas: [] },
    { nameEn: "Al-Jawf", nameAr: "الجوف", areas: [] },
    { nameEn: "Al-Qassim", nameAr: "القصيم", areas: [
      { nameEn: "Buraydah", nameAr: "بريدة" },
      { nameEn: "Unayzah", nameAr: "عنيزة" },
    ] },
  ],
  "Jordan": [
    { nameEn: "Amman", nameAr: "عمّان", areas: [
      { nameEn: "Abdali", nameAr: "العبدلي" },
      { nameEn: "Jabal Amman", nameAr: "جبل عمان" },
      { nameEn: "Shmeisani", nameAr: "الشميساني" },
      { nameEn: "Abdoun", nameAr: "عبدون" },
      { nameEn: "Sweifieh", nameAr: "الصويفية" },
      { nameEn: "Marj Al Hamam", nameAr: "مرج الحمام" },
      { nameEn: "Tabarbour", nameAr: "طبربور" },
      { nameEn: "Al Hashmi", nameAr: "الهاشمي" },
      { nameEn: "Sahab", nameAr: "سحاب" },
    ] },
    { nameEn: "Irbid", nameAr: "إربد", areas: [
      { nameEn: "Irbid City", nameAr: "مدينة إربد" },
      { nameEn: "Al Ramtha", nameAr: "الرمثا" },
    ] },
    { nameEn: "Zarqa", nameAr: "الزرقاء", areas: [
      { nameEn: "Zarqa City", nameAr: "مدينة الزرقاء" },
      { nameEn: "Russeifa", nameAr: "الرصيفة" },
    ] },
    { nameEn: "Mafraq", nameAr: "المفرق", areas: [] },
    { nameEn: "Balqa", nameAr: "البلقاء", areas: [] },
    { nameEn: "Madaba", nameAr: "مادبا", areas: [] },
    { nameEn: "Karak", nameAr: "الكرك", areas: [] },
    { nameEn: "Tafilah", nameAr: "الطفيلة", areas: [] },
    { nameEn: "Maan", nameAr: "معان", areas: [] },
    { nameEn: "Aqaba", nameAr: "العقبة", areas: [
      { nameEn: "Aqaba City", nameAr: "مدينة العقبة" },
    ] },
    { nameEn: "Jerash", nameAr: "جرش", areas: [] },
    { nameEn: "Ajloun", nameAr: "عجلون", areas: [] },
  ],
  "UAE": [
    { nameEn: "Abu Dhabi", nameAr: "أبو ظبي", areas: [
      { nameEn: "Abu Dhabi Island", nameAr: "جزيرة أبو ظبي" },
      { nameEn: "Al Ain", nameAr: "العين" },
      { nameEn: "Khalifa City", nameAr: "مدينة خليفة" },
      { nameEn: "Saadiyat Island", nameAr: "جزيرة السعديات" },
      { nameEn: "Yas Island", nameAr: "جزيرة ياس" },
      { nameEn: "Ruwais", nameAr: "الرويس" },
      { nameEn: "Madinat Zayed", nameAr: "مدينة زايد" },
    ] },
    { nameEn: "Dubai", nameAr: "دبي", areas: [
      { nameEn: "Deira", nameAr: "ديرة" },
      { nameEn: "Bur Dubai", nameAr: "بر دبي" },
      { nameEn: "Jumeirah", nameAr: "جميرا" },
      { nameEn: "Dubai Marina", nameAr: "مرسى دبي" },
      { nameEn: "Downtown Dubai", nameAr: "وسط مدينة دبي" },
      { nameEn: "Al Barsha", nameAr: "البرشاء" },
      { nameEn: "Karama", nameAr: "الكرامة" },
      { nameEn: "Al Qusais", nameAr: "القصيص" },
      { nameEn: "International City", nameAr: "المدينة العالمية" },
      { nameEn: "Silicon Oasis", nameAr: "واحة دبي للسيليكون" },
    ] },
    { nameEn: "Sharjah", nameAr: "الشارقة", areas: [
      { nameEn: "Sharjah City", nameAr: "مدينة الشارقة" },
      { nameEn: "Al Majaz", nameAr: "المجاز" },
      { nameEn: "Al Nahda", nameAr: "النهضة" },
      { nameEn: "Al Taawun", nameAr: "التعاون" },
    ] },
    { nameEn: "Ajman", nameAr: "عجمان", areas: [
      { nameEn: "Ajman City", nameAr: "مدينة عجمان" },
      { nameEn: "Al Nuaimia", nameAr: "النعيمية" },
    ] },
    { nameEn: "Umm Al Quwain", nameAr: "أم القيوين", areas: [] },
    { nameEn: "Ras Al Khaimah", nameAr: "رأس الخيمة", areas: [
      { nameEn: "RAK City", nameAr: "مدينة رأس الخيمة" },
      { nameEn: "Al Hamra", nameAr: "الحمراء" },
    ] },
    { nameEn: "Fujairah", nameAr: "الفجيرة", areas: [
      { nameEn: "Fujairah City", nameAr: "مدينة الفجيرة" },
    ] },
  ],
  "Kuwait": [
    { nameEn: "Al Asimah", nameAr: "العاصمة", areas: [
      { nameEn: "Kuwait City", nameAr: "مدينة الكويت" },
      { nameEn: "Sharq", nameAr: "شرق" },
      { nameEn: "Dasman", nameAr: "دسمان" },
      { nameEn: "Salmiya", nameAr: "السالمية" },
    ] },
    { nameEn: "Hawalli", nameAr: "حولي", areas: [
      { nameEn: "Hawalli City", nameAr: "مدينة حولي" },
      { nameEn: "Salmiya", nameAr: "السالمية" },
      { nameEn: "Mishref", nameAr: "مشرف" },
    ] },
    { nameEn: "Al Farwaniyah", nameAr: "الفروانية", areas: [
      { nameEn: "Farwaniya City", nameAr: "مدينة الفروانية" },
      { nameEn: "Jleeb Al Shuyoukh", nameAr: "جليب الشيوخ" },
      { nameEn: "Khaitan", nameAr: "خيطان" },
    ] },
    { nameEn: "Al Ahmadi", nameAr: "الأحمدي", areas: [
      { nameEn: "Ahmadi City", nameAr: "مدينة الأحمدي" },
      { nameEn: "Mangaf", nameAr: "المنقف" },
      { nameEn: "Fahaheel", nameAr: "الفحاحيل" },
    ] },
    { nameEn: "Jahra", nameAr: "الجهراء", areas: [
      { nameEn: "Jahra City", nameAr: "مدينة الجهراء" },
    ] },
    { nameEn: "Mubarak Al-Kabeer", nameAr: "مبارك الكبير", areas: [] },
  ],
  "Bahrain": [
    { nameEn: "Capital", nameAr: "العاصمة", areas: [
      { nameEn: "Manama", nameAr: "المنامة" },
      { nameEn: "Juffair", nameAr: "الجفير" },
      { nameEn: "Adliya", nameAr: "العدلية" },
      { nameEn: "Seef", nameAr: "السيف" },
    ] },
    { nameEn: "Muharraq", nameAr: "المحرق", areas: [
      { nameEn: "Muharraq City", nameAr: "مدينة المحرق" },
      { nameEn: "Arad", nameAr: "عراد" },
      { nameEn: "Hidd", nameAr: "الحد" },
    ] },
    { nameEn: "Northern", nameAr: "الشمالية", areas: [
      { nameEn: "Budaiya", nameAr: "البديع" },
      { nameEn: "Saar", nameAr: "سار" },
      { nameEn: "Hamad Town", nameAr: "مدينة حمد" },
    ] },
    { nameEn: "Southern", nameAr: "الجنوبية", areas: [
      { nameEn: "Isa Town", nameAr: "مدينة عيسى" },
      { nameEn: "Riffa", nameAr: "الرفاع" },
      { nameEn: "Zallaq", nameAr: "الزلاق" },
    ] },
  ],
  "Qatar": [
    { nameEn: "Doha", nameAr: "الدوحة", areas: [
      { nameEn: "West Bay", nameAr: "الخليج الغربي" },
      { nameEn: "The Pearl", nameAr: "اللؤلؤة" },
      { nameEn: "Lusail", nameAr: "لوسيل" },
      { nameEn: "Al Sadd", nameAr: "السد" },
      { nameEn: "Souq Waqif", nameAr: "سوق واقف" },
    ] },
    { nameEn: "Al Rayyan", nameAr: "الريان", areas: [
      { nameEn: "Al Rayyan City", nameAr: "مدينة الريان" },
      { nameEn: "Education City", nameAr: "المدينة التعليمية" },
    ] },
    { nameEn: "Al Wakrah", nameAr: "الوكرة", areas: [
      { nameEn: "Al Wakrah City", nameAr: "مدينة الوكرة" },
    ] },
    { nameEn: "Al Khor", nameAr: "الخور", areas: [] },
    { nameEn: "Al Shamal", nameAr: "الشمال", areas: [] },
    { nameEn: "Al Daayen", nameAr: "الضعاين", areas: [] },
    { nameEn: "Umm Salal", nameAr: "أم صلال", areas: [] },
    { nameEn: "Al Shahaniya", nameAr: "الشحانية", areas: [] },
  ],
  "Oman": [
    { nameEn: "Muscat", nameAr: "مسقط", areas: [
      { nameEn: "Muscat City", nameAr: "مدينة مسقط" },
      { nameEn: "Muttrah", nameAr: "مطرح" },
      { nameEn: "Ruwi", nameAr: "روي" },
      { nameEn: "Al Khuwair", nameAr: "الخوير" },
      { nameEn: "Seeb", nameAr: "السيب" },
      { nameEn: "Bawshar", nameAr: "بوشر" },
    ] },
    { nameEn: "Dhofar", nameAr: "ظفار", areas: [
      { nameEn: "Salalah", nameAr: "صلالة" },
    ] },
    { nameEn: "Ad Dakhiliyah", nameAr: "الداخلية", areas: [
      { nameEn: "Nizwa", nameAr: "نزوى" },
      { nameEn: "Bahla", nameAr: "بهلا" },
    ] },
    { nameEn: "North Al Batinah", nameAr: "شمال الباطنة", areas: [
      { nameEn: "Sohar", nameAr: "صحار" },
      { nameEn: "Shinas", nameAr: "شناص" },
    ] },
    { nameEn: "South Al Batinah", nameAr: "جنوب الباطنة", areas: [] },
    { nameEn: "Ash Sharqiyah North", nameAr: "شمال الشرقية", areas: [] },
    { nameEn: "Ash Sharqiyah South", nameAr: "جنوب الشرقية", areas: [] },
    { nameEn: "Ad Dhahirah", nameAr: "الظاهرة", areas: [] },
    { nameEn: "Al Buraimi", nameAr: "البريمي", areas: [] },
    { nameEn: "Al Wusta", nameAr: "الوسطى", areas: [] },
    { nameEn: "Musandam", nameAr: "مسندم", areas: [] },
  ],
  "Iraq": [
    { nameEn: "Baghdad", nameAr: "بغداد", areas: [
      { nameEn: "Karkh", nameAr: "الكرخ" },
      { nameEn: "Rusafa", nameAr: "الرصافة" },
      { nameEn: "Kadhimiya", nameAr: "الكاظمية" },
      { nameEn: "Adhamiyah", nameAr: "الأعظمية" },
      { nameEn: "Mansour", nameAr: "المنصور" },
      { nameEn: "Sadr City", nameAr: "مدينة الصدر" },
    ] },
    { nameEn: "Basra", nameAr: "البصرة", areas: [
      { nameEn: "Basra City", nameAr: "مدينة البصرة" },
      { nameEn: "Abu Al Khaseeb", nameAr: "أبو الخصيب" },
      { nameEn: "Zubair", nameAr: "الزبير" },
    ] },
    { nameEn: "Nineveh", nameAr: "نينوى", areas: [
      { nameEn: "Mosul", nameAr: "الموصل" },
      { nameEn: "Tal Afar", nameAr: "تلعفر" },
    ] },
    { nameEn: "Erbil", nameAr: "أربيل", areas: [
      { nameEn: "Erbil City", nameAr: "مدينة أربيل" },
    ] },
    { nameEn: "Sulaymaniyah", nameAr: "السليمانية", areas: [
      { nameEn: "Sulaymaniyah City", nameAr: "مدينة السليمانية" },
    ] },
    { nameEn: "Dohuk", nameAr: "دهوك", areas: [] },
    { nameEn: "Kirkuk", nameAr: "كركوك", areas: [
      { nameEn: "Kirkuk City", nameAr: "مدينة كركوك" },
    ] },
    { nameEn: "Anbar", nameAr: "الأنبار", areas: [] },
    { nameEn: "Salah ad-Din", nameAr: "صلاح الدين", areas: [] },
    { nameEn: "Diyala", nameAr: "ديالى", areas: [] },
    { nameEn: "Wasit", nameAr: "واسط", areas: [] },
    { nameEn: "Maysan", nameAr: "ميسان", areas: [] },
    { nameEn: "Dhi Qar", nameAr: "ذي قار", areas: [] },
    { nameEn: "Muthanna", nameAr: "المثنى", areas: [] },
    { nameEn: "Qadisiyyah", nameAr: "القادسية", areas: [] },
    { nameEn: "Babil", nameAr: "بابل", areas: [
      { nameEn: "Hillah", nameAr: "الحلة" },
    ] },
    { nameEn: "Karbala", nameAr: "كربلاء", areas: [
      { nameEn: "Karbala City", nameAr: "مدينة كربلاء" },
    ] },
    { nameEn: "Najaf", nameAr: "النجف", areas: [
      { nameEn: "Najaf City", nameAr: "مدينة النجف" },
    ] },
    { nameEn: "Halabja", nameAr: "حلبجة", areas: [] },
  ],
  "Syria": [
    { nameEn: "Damascus", nameAr: "دمشق", areas: [
      { nameEn: "Old City", nameAr: "المدينة القديمة" },
      { nameEn: "Mazzeh", nameAr: "المزة" },
      { nameEn: "Malki", nameAr: "المالكي" },
      { nameEn: "Abu Rummaneh", nameAr: "أبو رمانة" },
      { nameEn: "Kafarsouseh", nameAr: "كفرسوسة" },
    ] },
    { nameEn: "Rif Dimashq", nameAr: "ريف دمشق", areas: [
      { nameEn: "Jaramana", nameAr: "جرمانا" },
      { nameEn: "Daraya", nameAr: "داريا" },
    ] },
    { nameEn: "Aleppo", nameAr: "حلب", areas: [
      { nameEn: "Aleppo City", nameAr: "مدينة حلب" },
      { nameEn: "Al Bab", nameAr: "الباب" },
    ] },
    { nameEn: "Homs", nameAr: "حمص", areas: [
      { nameEn: "Homs City", nameAr: "مدينة حمص" },
      { nameEn: "Palmyra", nameAr: "تدمر" },
    ] },
    { nameEn: "Hama", nameAr: "حماة", areas: [] },
    { nameEn: "Latakia", nameAr: "اللاذقية", areas: [
      { nameEn: "Latakia City", nameAr: "مدينة اللاذقية" },
    ] },
    { nameEn: "Tartus", nameAr: "طرطوس", areas: [
      { nameEn: "Tartus City", nameAr: "مدينة طرطوس" },
    ] },
    { nameEn: "Idlib", nameAr: "إدلب", areas: [] },
    { nameEn: "Deir ez-Zor", nameAr: "دير الزور", areas: [] },
    { nameEn: "Hasakah", nameAr: "الحسكة", areas: [] },
    { nameEn: "Raqqa", nameAr: "الرقة", areas: [] },
    { nameEn: "Daraa", nameAr: "درعا", areas: [] },
    { nameEn: "Sweida", nameAr: "السويداء", areas: [] },
    { nameEn: "Quneitra", nameAr: "القنيطرة", areas: [] },
  ],
  "Lebanon": [
    { nameEn: "Beirut", nameAr: "بيروت", areas: [
      { nameEn: "Hamra", nameAr: "الحمراء" },
      { nameEn: "Achrafieh", nameAr: "الأشرفية" },
      { nameEn: "Verdun", nameAr: "فردان" },
      { nameEn: "Ras Beirut", nameAr: "رأس بيروت" },
      { nameEn: "Gemmayzeh", nameAr: "الجميزة" },
    ] },
    { nameEn: "Mount Lebanon", nameAr: "جبل لبنان", areas: [
      { nameEn: "Jounieh", nameAr: "جونية" },
      { nameEn: "Baabda", nameAr: "بعبدا" },
      { nameEn: "Aley", nameAr: "عاليه" },
      { nameEn: "Byblos", nameAr: "جبيل" },
      { nameEn: "Chouf", nameAr: "الشوف" },
    ] },
    { nameEn: "North Lebanon", nameAr: "لبنان الشمالي", areas: [
      { nameEn: "Tripoli", nameAr: "طرابلس" },
      { nameEn: "Bcharre", nameAr: "بشري" },
      { nameEn: "Zgharta", nameAr: "زغرتا" },
    ] },
    { nameEn: "South Lebanon", nameAr: "لبنان الجنوبي", areas: [
      { nameEn: "Sidon", nameAr: "صيدا" },
      { nameEn: "Tyre", nameAr: "صور" },
    ] },
    { nameEn: "Beqaa", nameAr: "البقاع", areas: [
      { nameEn: "Zahle", nameAr: "زحلة" },
      { nameEn: "Chtaura", nameAr: "شتورة" },
    ] },
    { nameEn: "Nabatieh", nameAr: "النبطية", areas: [] },
    { nameEn: "Akkar", nameAr: "عكار", areas: [] },
    { nameEn: "Baalbek-Hermel", nameAr: "بعلبك الهرمل", areas: [] },
    { nameEn: "Keserwan-Jbeil", nameAr: "كسروان جبيل", areas: [] },
  ],
  "Palestine": [
    { nameEn: "Jerusalem", nameAr: "القدس", areas: [
      { nameEn: "Old City", nameAr: "البلدة القديمة" },
      { nameEn: "Al Tur", nameAr: "الطور" },
      { nameEn: "Silwan", nameAr: "سلوان" },
    ] },
    { nameEn: "Ramallah and Al-Bireh", nameAr: "رام الله والبيرة", areas: [
      { nameEn: "Ramallah City", nameAr: "مدينة رام الله" },
      { nameEn: "Al-Bireh", nameAr: "البيرة" },
      { nameEn: "Birzeit", nameAr: "بيرزيت" },
    ] },
    { nameEn: "Nablus", nameAr: "نابلس", areas: [
      { nameEn: "Nablus City", nameAr: "مدينة نابلس" },
    ] },
    { nameEn: "Hebron", nameAr: "الخليل", areas: [
      { nameEn: "Hebron City", nameAr: "مدينة الخليل" },
    ] },
    { nameEn: "Bethlehem", nameAr: "بيت لحم", areas: [
      { nameEn: "Bethlehem City", nameAr: "مدينة بيت لحم" },
      { nameEn: "Beit Jala", nameAr: "بيت جالا" },
    ] },
    { nameEn: "Jenin", nameAr: "جنين", areas: [] },
    { nameEn: "Tulkarm", nameAr: "طولكرم", areas: [] },
    { nameEn: "Qalqilya", nameAr: "قلقيلية", areas: [] },
    { nameEn: "Salfit", nameAr: "سلفيت", areas: [] },
    { nameEn: "Tubas", nameAr: "طوباس", areas: [] },
    { nameEn: "Jericho", nameAr: "أريحا", areas: [] },
    { nameEn: "Gaza", nameAr: "غزة", areas: [
      { nameEn: "Gaza City", nameAr: "مدينة غزة" },
      { nameEn: "Al Rimal", nameAr: "الرمال" },
    ] },
    { nameEn: "North Gaza", nameAr: "شمال غزة", areas: [] },
    { nameEn: "Deir al-Balah", nameAr: "دير البلح", areas: [] },
    { nameEn: "Khan Yunis", nameAr: "خان يونس", areas: [
      { nameEn: "Khan Yunis City", nameAr: "مدينة خان يونس" },
    ] },
    { nameEn: "Rafah", nameAr: "رفح", areas: [] },
  ],
  "Yemen": [
    { nameEn: "Sanaa City", nameAr: "أمانة العاصمة", areas: [
      { nameEn: "Old Sanaa", nameAr: "صنعاء القديمة" },
      { nameEn: "Hadda", nameAr: "حدة" },
      { nameEn: "Al Zubairi", nameAr: "الزبيري" },
    ] },
    { nameEn: "Sanaa", nameAr: "صنعاء", areas: [] },
    { nameEn: "Aden", nameAr: "عدن", areas: [
      { nameEn: "Crater", nameAr: "كريتر" },
      { nameEn: "Al Mansoura", nameAr: "المنصورة" },
      { nameEn: "Khormaksar", nameAr: "خور مكسر" },
    ] },
    { nameEn: "Taiz", nameAr: "تعز", areas: [
      { nameEn: "Taiz City", nameAr: "مدينة تعز" },
    ] },
    { nameEn: "Hodeidah", nameAr: "الحديدة", areas: [
      { nameEn: "Hodeidah City", nameAr: "مدينة الحديدة" },
    ] },
    { nameEn: "Ibb", nameAr: "إب", areas: [] },
    { nameEn: "Dhamar", nameAr: "ذمار", areas: [] },
    { nameEn: "Al Mahwit", nameAr: "المحويت", areas: [] },
    { nameEn: "Hajjah", nameAr: "حجة", areas: [] },
    { nameEn: "Amran", nameAr: "عمران", areas: [] },
    { nameEn: "Saadah", nameAr: "صعدة", areas: [] },
    { nameEn: "Al Jawf", nameAr: "الجوف", areas: [] },
    { nameEn: "Marib", nameAr: "مأرب", areas: [] },
    { nameEn: "Al Bayda", nameAr: "البيضاء", areas: [] },
    { nameEn: "Abyan", nameAr: "أبين", areas: [] },
    { nameEn: "Shabwah", nameAr: "شبوة", areas: [] },
    { nameEn: "Lahij", nameAr: "لحج", areas: [] },
    { nameEn: "Hadramaut", nameAr: "حضرموت", areas: [
      { nameEn: "Mukalla", nameAr: "المكلا" },
      { nameEn: "Shibam", nameAr: "شبام" },
      { nameEn: "Seiyun", nameAr: "سيئون" },
    ] },
    { nameEn: "Al Mahrah", nameAr: "المهرة", areas: [] },
    { nameEn: "Raymah", nameAr: "ريمة", areas: [] },
    { nameEn: "Socotra", nameAr: "سقطرى", areas: [] },
    { nameEn: "Ad Dhalee", nameAr: "الضالع", areas: [] },
  ],
  "Libya": [
    { nameEn: "Tripoli", nameAr: "طرابلس", areas: [
      { nameEn: "Tripoli Center", nameAr: "طرابلس المركز" },
      { nameEn: "Ain Zara", nameAr: "عين زارة" },
      { nameEn: "Abu Salim", nameAr: "أبو سليم" },
      { nameEn: "Tajura", nameAr: "تاجوراء" },
      { nameEn: "Hay Al Andalus", nameAr: "حي الأندلس" },
    ] },
    { nameEn: "Benghazi", nameAr: "بنغازي", areas: [
      { nameEn: "Benghazi Center", nameAr: "بنغازي المركز" },
      { nameEn: "Al Fuwayhat", nameAr: "الفويهات" },
      { nameEn: "Al Sabri", nameAr: "الصابري" },
    ] },
    { nameEn: "Misrata", nameAr: "مصراتة", areas: [
      { nameEn: "Misrata City", nameAr: "مدينة مصراتة" },
    ] },
    { nameEn: "Zawiya", nameAr: "الزاوية", areas: [] },
    { nameEn: "Sirte", nameAr: "سرت", areas: [] },
    { nameEn: "Derna", nameAr: "درنة", areas: [] },
    { nameEn: "Sabha", nameAr: "سبها", areas: [
      { nameEn: "Sabha City", nameAr: "مدينة سبها" },
    ] },
    { nameEn: "Murzuq", nameAr: "مرزق", areas: [] },
    { nameEn: "Jabal al Akhdar", nameAr: "الجبل الأخضر", areas: [] },
    { nameEn: "Jabal al Gharbi", nameAr: "الجبل الغربي", areas: [] },
    { nameEn: "Marj", nameAr: "المرج", areas: [] },
    { nameEn: "Jafara", nameAr: "الجفارة", areas: [] },
    { nameEn: "Nalut", nameAr: "نالوت", areas: [] },
    { nameEn: "Nuqat al Khams", nameAr: "النقاط الخمس", areas: [] },
    { nameEn: "Murqub", nameAr: "المرقب", areas: [] },
    { nameEn: "Al Wahat", nameAr: "الواحات", areas: [] },
    { nameEn: "Kufra", nameAr: "الكفرة", areas: [] },
    { nameEn: "Ghat", nameAr: "غات", areas: [] },
    { nameEn: "Wadi al Shatii", nameAr: "وادي الشاطئ", areas: [] },
    { nameEn: "Wadi al Hayaa", nameAr: "وادي الحياة", areas: [] },
    { nameEn: "Jufra", nameAr: "الجفرة", areas: [] },
    { nameEn: "Butnan", nameAr: "البطنان", areas: [] },
  ],
  "Tunisia": [
    { nameEn: "Tunis", nameAr: "تونس", areas: [
      { nameEn: "Tunis Center", nameAr: "تونس المركز" },
      { nameEn: "La Marsa", nameAr: "المرسى" },
      { nameEn: "Carthage", nameAr: "قرطاج" },
      { nameEn: "Sidi Bou Said", nameAr: "سيدي بوسعيد" },
    ] },
    { nameEn: "Ariana", nameAr: "أريانة", areas: [
      { nameEn: "Ariana City", nameAr: "مدينة أريانة" },
    ] },
    { nameEn: "Ben Arous", nameAr: "بن عروس", areas: [] },
    { nameEn: "Manouba", nameAr: "منوبة", areas: [] },
    { nameEn: "Nabeul", nameAr: "نابل", areas: [
      { nameEn: "Hammamet", nameAr: "الحمامات" },
      { nameEn: "Nabeul City", nameAr: "مدينة نابل" },
    ] },
    { nameEn: "Zaghouan", nameAr: "زغوان", areas: [] },
    { nameEn: "Bizerte", nameAr: "بنزرت", areas: [] },
    { nameEn: "Beja", nameAr: "باجة", areas: [] },
    { nameEn: "Jendouba", nameAr: "جندوبة", areas: [] },
    { nameEn: "Kef", nameAr: "الكاف", areas: [] },
    { nameEn: "Siliana", nameAr: "سليانة", areas: [] },
    { nameEn: "Sousse", nameAr: "سوسة", areas: [] },
    { nameEn: "Monastir", nameAr: "المنستير", areas: [
      { nameEn: "Sousse City", nameAr: "مدينة سوسة" },
      { nameEn: "Port El Kantaoui", nameAr: "بورت القنطاوي" },
    ] },
    { nameEn: "Mahdia", nameAr: "المهدية", areas: [] },
    { nameEn: "Sfax", nameAr: "صفاقس", areas: [] },
    { nameEn: "Kairouan", nameAr: "القيروان", areas: [
      { nameEn: "Sfax City", nameAr: "مدينة صفاقس" },
    ] },
    { nameEn: "Kasserine", nameAr: "القصرين", areas: [] },
    { nameEn: "Sidi Bouzid", nameAr: "سيدي بوزيد", areas: [] },
    { nameEn: "Gabes", nameAr: "قابس", areas: [] },
    { nameEn: "Medenine", nameAr: "مدنين", areas: [] },
    { nameEn: "Tataouine", nameAr: "تطاوين", areas: [] },
    { nameEn: "Gafsa", nameAr: "قفصة", areas: [] },
    { nameEn: "Tozeur", nameAr: "توزر", areas: [] },
    { nameEn: "Kebili", nameAr: "قبلي", areas: [] },
  ],
  "Algeria": [
    { nameEn: "Algiers", nameAr: "الجزائر العاصمة", areas: [
      { nameEn: "Bab El Oued", nameAr: "باب الوادي" },
      { nameEn: "Kouba", nameAr: "القبة" },
      { nameEn: "Hussein Dey", nameAr: "حسين داي" },
      { nameEn: "Hydra", nameAr: "حيدرة" },
      { nameEn: "Bir Mourad Rais", nameAr: "بئر مراد رايس" },
      { nameEn: "El Biar", nameAr: "الأبيار" },
    ] },
    { nameEn: "Oran", nameAr: "وهران", areas: [
      { nameEn: "Oran Center", nameAr: "وهران المركز" },
      { nameEn: "Ain Turk", nameAr: "عين الترك" },
      { nameEn: "Es Senia", nameAr: "السانية" },
    ] },
    { nameEn: "Constantine", nameAr: "قسنطينة", areas: [
      { nameEn: "Constantine City", nameAr: "مدينة قسنطينة" },
    ] },
    { nameEn: "Annaba", nameAr: "عنابة", areas: [
      { nameEn: "Annaba City", nameAr: "مدينة عنابة" },
    ] },
    { nameEn: "Blida", nameAr: "البليدة", areas: [] },
    { nameEn: "Batna", nameAr: "باتنة", areas: [] },
    { nameEn: "Setif", nameAr: "سطيف", areas: [
      { nameEn: "Setif City", nameAr: "مدينة سطيف" },
    ] },
    { nameEn: "Tlemcen", nameAr: "تلمسان", areas: [] },
    { nameEn: "Bejaia", nameAr: "بجاية", areas: [
      { nameEn: "Bejaia City", nameAr: "مدينة بجاية" },
    ] },
    { nameEn: "Tizi Ouzou", nameAr: "تيزي وزو", areas: [] },
    { nameEn: "Djelfa", nameAr: "الجلفة", areas: [] },
    { nameEn: "Biskra", nameAr: "بسكرة", areas: [] },
    { nameEn: "Skikda", nameAr: "سكيكدة", areas: [] },
    { nameEn: "Bechar", nameAr: "بشار", areas: [] },
    { nameEn: "Ouargla", nameAr: "ورقلة", areas: [] },
    { nameEn: "Mostaganem", nameAr: "مستغانم", areas: [] },
    { nameEn: "Medea", nameAr: "المدية", areas: [] },
    { nameEn: "Msila", nameAr: "المسيلة", areas: [] },
    { nameEn: "Mascara", nameAr: "معسكر", areas: [] },
    { nameEn: "Ghardaia", nameAr: "غرداية", areas: [] },
    { nameEn: "Chlef", nameAr: "الشلف", areas: [] },
    { nameEn: "Laghouat", nameAr: "الأغواط", areas: [] },
    { nameEn: "Oum El Bouaghi", nameAr: "أم البواقي", areas: [] },
    { nameEn: "Bouira", nameAr: "البويرة", areas: [] },
    { nameEn: "Tamanrasset", nameAr: "تمنراست", areas: [] },
    { nameEn: "Tebessa", nameAr: "تبسة", areas: [] },
    { nameEn: "Tiaret", nameAr: "تيارت", areas: [] },
    { nameEn: "Jijel", nameAr: "جيجل", areas: [] },
    { nameEn: "Saida", nameAr: "سعيدة", areas: [] },
    { nameEn: "Sidi Bel Abbes", nameAr: "سيدي بلعباس", areas: [] },
    { nameEn: "Guelma", nameAr: "قالمة", areas: [] },
    { nameEn: "El Bayadh", nameAr: "البيض", areas: [] },
    { nameEn: "Illizi", nameAr: "إليزي", areas: [] },
    { nameEn: "Bordj Bou Arreridj", nameAr: "برج بوعريريج", areas: [] },
    { nameEn: "Boumerdes", nameAr: "بومرداس", areas: [] },
    { nameEn: "El Tarf", nameAr: "الطارف", areas: [] },
    { nameEn: "Tindouf", nameAr: "تندوف", areas: [] },
    { nameEn: "Tissemsilt", nameAr: "تيسمسيلت", areas: [] },
    { nameEn: "El Oued", nameAr: "الوادي", areas: [] },
    { nameEn: "Khenchela", nameAr: "خنشلة", areas: [] },
    { nameEn: "Souk Ahras", nameAr: "سوق أهراس", areas: [] },
    { nameEn: "Tipaza", nameAr: "تيبازة", areas: [] },
    { nameEn: "Mila", nameAr: "ميلة", areas: [] },
    { nameEn: "Ain Defla", nameAr: "عين الدفلى", areas: [] },
    { nameEn: "Naama", nameAr: "النعامة", areas: [] },
    { nameEn: "Ain Temouchent", nameAr: "عين تموشنت", areas: [] },
    { nameEn: "Relizane", nameAr: "غليزان", areas: [] },
    { nameEn: "Adrar", nameAr: "أدرار", areas: [] },
  ],
  "Morocco": [
    { nameEn: "Casablanca-Settat", nameAr: "الدار البيضاء سطات", areas: [
      { nameEn: "Casablanca", nameAr: "الدار البيضاء" },
      { nameEn: "Ain Diab", nameAr: "عين الذياب" },
      { nameEn: "Maarif", nameAr: "المعاريف" },
      { nameEn: "Anfa", nameAr: "أنفا" },
      { nameEn: "Settat", nameAr: "سطات" },
      { nameEn: "Mohammedia", nameAr: "المحمدية" },
    ] },
    { nameEn: "Rabat-Sale-Kenitra", nameAr: "الرباط سلا القنيطرة", areas: [
      { nameEn: "Rabat", nameAr: "الرباط" },
      { nameEn: "Sale", nameAr: "سلا" },
      { nameEn: "Temara", nameAr: "تمارة" },
      { nameEn: "Kenitra", nameAr: "القنيطرة" },
    ] },
    { nameEn: "Marrakech-Safi", nameAr: "مراكش آسفي", areas: [
      { nameEn: "Marrakech", nameAr: "مراكش" },
      { nameEn: "Essaouira", nameAr: "الصويرة" },
      { nameEn: "Safi", nameAr: "آسفي" },
    ] },
    { nameEn: "Fes-Meknes", nameAr: "فاس مكناس", areas: [
      { nameEn: "Fes", nameAr: "فاس" },
      { nameEn: "Meknes", nameAr: "مكناس" },
    ] },
    { nameEn: "Tanger-Tetouan-Al Hoceima", nameAr: "طنجة تطوان الحسيمة", areas: [
      { nameEn: "Tangier", nameAr: "طنجة" },
      { nameEn: "Tetouan", nameAr: "تطوان" },
      { nameEn: "Chefchaouen", nameAr: "شفشاون" },
    ] },
    { nameEn: "Oriental", nameAr: "الشرق", areas: [] },
    { nameEn: "Beni Mellal-Khenifra", nameAr: "بني ملال خنيفرة", areas: [] },
    { nameEn: "Draa-Tafilalet", nameAr: "درعة تافيلالت", areas: [] },
    { nameEn: "Souss-Massa", nameAr: "سوس ماسة", areas: [
      { nameEn: "Agadir", nameAr: "أكادير" },
      { nameEn: "Taroudant", nameAr: "تارودانت" },
    ] },
    { nameEn: "Guelmim-Oued Noun", nameAr: "كلميم واد نون", areas: [] },
    { nameEn: "Laayoune-Sakia El Hamra", nameAr: "العيون الساقية الحمراء", areas: [] },
    { nameEn: "Dakhla-Oued Ed-Dahab", nameAr: "الداخلة وادي الذهب", areas: [] },
  ],
  "Sudan": [
    { nameEn: "Khartoum", nameAr: "الخرطوم", areas: [
      { nameEn: "Khartoum City", nameAr: "مدينة الخرطوم" },
      { nameEn: "Omdurman", nameAr: "أم درمان" },
      { nameEn: "Bahri", nameAr: "بحري" },
      { nameEn: "Khartoum North", nameAr: "الخرطوم بحري" },
    ] },
    { nameEn: "Al Jazirah", nameAr: "الجزيرة", areas: [] },
    { nameEn: "White Nile", nameAr: "النيل الأبيض", areas: [] },
    { nameEn: "Blue Nile", nameAr: "النيل الأزرق", areas: [] },
    { nameEn: "Northern", nameAr: "الشمالية", areas: [] },
    { nameEn: "River Nile", nameAr: "نهر النيل", areas: [] },
    { nameEn: "Red Sea", nameAr: "البحر الأحمر", areas: [] },
    { nameEn: "Kassala", nameAr: "كسلا", areas: [] },
    { nameEn: "Al Qadarif", nameAr: "القضارف", areas: [] },
    { nameEn: "Sennar", nameAr: "سنار", areas: [] },
    { nameEn: "North Kordofan", nameAr: "شمال كردفان", areas: [] },
    { nameEn: "South Kordofan", nameAr: "جنوب كردفان", areas: [] },
    { nameEn: "West Kordofan", nameAr: "غرب كردفان", areas: [] },
    { nameEn: "North Darfur", nameAr: "شمال دارفور", areas: [] },
    { nameEn: "South Darfur", nameAr: "جنوب دارفور", areas: [] },
    { nameEn: "West Darfur", nameAr: "غرب دارفور", areas: [] },
    { nameEn: "East Darfur", nameAr: "شرق دارفور", areas: [] },
    { nameEn: "Central Darfur", nameAr: "وسط دارفور", areas: [] },
  ],
  "Somalia": [
    { nameEn: "Banaadir", nameAr: "بنادر", areas: [
      { nameEn: "Mogadishu", nameAr: "مقديشو" },
      { nameEn: "Hodan", nameAr: "هودن" },
      { nameEn: "Hamar Weyne", nameAr: "حمر وين" },
    ] },
    { nameEn: "Bari", nameAr: "باري", areas: [
      { nameEn: "Bosaso", nameAr: "بوصاصو" },
    ] },
    { nameEn: "Bay", nameAr: "باي", areas: [
      { nameEn: "Baidoa", nameAr: "بيدوا" },
    ] },
    { nameEn: "Bakool", nameAr: "بكول", areas: [] },
    { nameEn: "Galguduud", nameAr: "غلغدود", areas: [] },
    { nameEn: "Gedo", nameAr: "غيدو", areas: [] },
    { nameEn: "Hiiraan", nameAr: "حيران", areas: [] },
    { nameEn: "Lower Juba", nameAr: "جوبا السفلى", areas: [] },
    { nameEn: "Middle Juba", nameAr: "جوبا الوسطى", areas: [] },
    { nameEn: "Lower Shabelle", nameAr: "شبيلي السفلى", areas: [] },
    { nameEn: "Middle Shabelle", nameAr: "شبيلي الوسطى", areas: [] },
    { nameEn: "Mudug", nameAr: "مدغ", areas: [] },
    { nameEn: "Nugaal", nameAr: "نغال", areas: [] },
    { nameEn: "Sanaag", nameAr: "سناغ", areas: [] },
    { nameEn: "Sool", nameAr: "صول", areas: [] },
    { nameEn: "Togdheer", nameAr: "توغدير", areas: [] },
    { nameEn: "Woqooyi Galbeed", nameAr: "ووقويي غلبيد", areas: [] },
    { nameEn: "Awdal", nameAr: "أودل", areas: [] },
  ],
  "Mauritania": [
    { nameEn: "Nouakchott Nord", nameAr: "نواكشوط الشمالية", areas: [
      { nameEn: "Dar Naim", nameAr: "دار النعيم" },
      { nameEn: "Teyarett", nameAr: "تيارت" },
    ] },
    { nameEn: "Nouakchott Ouest", nameAr: "نواكشوط الغربية", areas: [
      { nameEn: "Tevragh Zeina", nameAr: "تفرغ زينة" },
      { nameEn: "Ksar", nameAr: "لكصر" },
    ] },
    { nameEn: "Nouakchott Sud", nameAr: "نواكشوط الجنوبية", areas: [
      { nameEn: "Arafat", nameAr: "عرفات" },
      { nameEn: "El Mina", nameAr: "الميناء" },
    ] },
    { nameEn: "Adrar", nameAr: "آدرار", areas: [] },
    { nameEn: "Assaba", nameAr: "لعصابة", areas: [] },
    { nameEn: "Brakna", nameAr: "البراكنة", areas: [] },
    { nameEn: "Dakhlet Nouadhibou", nameAr: "داخلت نواذيبو", areas: [] },
    { nameEn: "Gorgol", nameAr: "كوركول", areas: [] },
    { nameEn: "Guidimaka", nameAr: "كيدي ماغا", areas: [] },
    { nameEn: "Hodh Ech Chargui", nameAr: "الحوض الشرقي", areas: [] },
    { nameEn: "Hodh El Gharbi", nameAr: "الحوض الغربي", areas: [] },
    { nameEn: "Inchiri", nameAr: "إينشيري", areas: [] },
    { nameEn: "Tagant", nameAr: "تكانت", areas: [] },
    { nameEn: "Tiris Zemmour", nameAr: "تيرس زمور", areas: [] },
    { nameEn: "Trarza", nameAr: "الترارزة", areas: [] },
  ],
  "Djibouti": [
    { nameEn: "Djibouti", nameAr: "جيبوتي", areas: [
      { nameEn: "Djibouti City", nameAr: "مدينة جيبوتي" },
      { nameEn: "Balbala", nameAr: "بلبلة" },
    ] },
    { nameEn: "Ali Sabieh", nameAr: "علي صبيح", areas: [
      { nameEn: "Ali Sabieh City", nameAr: "مدينة علي صبيح" },
    ] },
    { nameEn: "Dikhil", nameAr: "دخيل", areas: [] },
    { nameEn: "Tadjourah", nameAr: "تاجورة", areas: [] },
    { nameEn: "Obock", nameAr: "أوبوك", areas: [] },
    { nameEn: "Arta", nameAr: "أرتا", areas: [] },
  ],
  "Comoros": [
    { nameEn: "Grande Comore", nameAr: "القمر الكبرى", areas: [
      { nameEn: "Moroni", nameAr: "موروني" },
      { nameEn: "Mitsamiouli", nameAr: "ميتساميولي" },
    ] },
    { nameEn: "Anjouan", nameAr: "أنجوان", areas: [
      { nameEn: "Mutsamudu", nameAr: "موتسامودو" },
    ] },
    { nameEn: "Moheli", nameAr: "موهيلي", areas: [
      { nameEn: "Fomboni", nameAr: "فومبوني" },
    ] },
  ],
};
